"""
Tests for the second hardware-efficient ansatz family (QNNConfig.ansatz = "B").

(i)   ansatz "A" (the default) is BIT-IDENTICAL to the pre-change code path: we
      compare prepare()/full_state()/full_features()/subcircuit features against
      tests/data/ansatz_A_reference.npz, which was generated by the ORIGINAL
      circuits.py BEFORE the ansatz field existed.
(ii)  ansatz "B": exact gate-cut reconstruction == uncut circuit to < 1e-10
      (same logic as tests/test_cutting.py), including the fixed phi = pi/2 case.
(iii) ansatz "B" states are genuinely different from "A" for identical params.
"""
import os
from dataclasses import replace
import numpy as np

from lfqml import qsim, cutting
from lfqml.circuits import (QNNConfig, init_params, param_count, prepare, full_state,
                            full_features, default_observables, local_var_layer)

REF = os.path.join(os.path.dirname(__file__), "data", "ansatz_A_reference.npz")
REF_CONFIGS = [(2, 2, 2, 2, True), (1, 1, 1, 2, True), (3, 2, 2, 1, False), (2, 3, 1, 2, True)]


def test_ansatz_A_bit_identical_to_pre_change_reference():
    ref = np.load(REF)
    n_checked = 0
    for i, (nA, nB, cuts, depth, tc) in enumerate(REF_CONFIGS):
        cfg = QNNConfig(n_A=nA, n_B=nB, depth=depth, n_cuts=cuts, trainable_coupling=tc)
        assert cfg.ansatz == "A"                      # default unchanged
        obs = default_observables(cfg)
        for t in range(3):
            key = f"c{i}_t{t}"
            p, x = ref[key + "_params"], ref[key + "_x"]
            pc = prepare(cfg, p, x)
            assert np.array_equal(pc.psiA_pre, ref[key + "_psiA"])
            assert np.array_equal(pc.psiB_pre, ref[key + "_psiB"])
            assert np.array_equal(full_state(pc), ref[key + "_full"])
            assert np.array_equal(full_features(pc, obs), ref[key + "_feat"])
            assert np.array_equal(cutting.subcircuit_raw_features(pc), ref[key + "_sub"])
            n_checked += 1
    assert n_checked == 12
    # the positional 4-arg signature of local_var_layer still works and equals ansatz "A"
    psi = qsim.zero_state(3)
    blk = np.linspace(-1, 1, 3 * 2 * 2)
    assert np.array_equal(local_var_layer(psi, blk, 3, 2), local_var_layer(psi, blk, 3, 2, "A"))


def test_ansatz_B_param_layout_matches_A():
    for (nA, nB, cuts, depth, tc) in REF_CONFIGS:
        cA = QNNConfig(n_A=nA, n_B=nB, depth=depth, n_cuts=cuts, trainable_coupling=tc)
        cB = replace(cA, ansatz="B")
        assert param_count(cA) == param_count(cB)
        assert np.array_equal(init_params(cA, seed=4), init_params(cB, seed=4))
    # fixed max-entangling coupling for the paper's "B" setting
    cB = QNNConfig(2, 2, depth=2, n_cuts=2, ansatz="B", trainable_coupling=False,
                   coupling_init=np.pi / 2)
    assert param_count(cB) == 2 * (2 * 2 * 2) + 2 * (2 * 2 * 2)     # no coupling param
    # dataclasses.replace (used by train_fusion_independent) keeps the ansatz
    assert replace(cB, trainable_coupling=False, coupling_init=0.0).ansatz == "B"


def test_ansatz_B_exact_reconstruction_equals_uncut():
    rng = np.random.default_rng(7)
    for (nA, nB, cuts, depth) in [(2, 2, 1, 1), (2, 2, 2, 1), (3, 2, 2, 2), (2, 3, 1, 2), (1, 1, 1, 2)]:
        for tc in (True, False):
            cfg = QNNConfig(n_A=nA, n_B=nB, depth=depth, n_cuts=cuts, ansatz="B",
                            trainable_coupling=tc, coupling_init=np.pi / 2)
            obs = default_observables(cfg)
            for trial in range(5):
                params = init_params(cfg, seed=trial) + 0.5 * rng.standard_normal(param_count(cfg))
                x = rng.uniform(-np.pi, np.pi, size=cfg.n)
                pc = prepare(cfg, params, x)
                f_uncut = full_features(pc, obs)
                cd = cutting.build_cut(pc)
                f_recon = cutting.reconstruct_features(cd, obs, Q=1.0)
                err = np.max(np.abs(f_uncut - f_recon))
                assert err < 1e-10, f"cfg={cfg} trial={trial} err={err}"
                if not tc:
                    assert pc.phi == np.pi / 2
                    # physical QPD overhead per RZZ(phi) cut = (1 + 2|sin phi|)^2 = 9
                    assert abs((1 + 2 * abs(np.sin(pc.phi))) ** 2 - 9.0) < 1e-12


def test_ansatz_B_differs_from_A():
    rng = np.random.default_rng(11)
    cfgA = QNNConfig(n_A=2, n_B=2, depth=2, n_cuts=2)
    cfgB = replace(cfgA, ansatz="B")
    obs = default_observables(cfgA)
    for trial in range(5):
        p = init_params(cfgA, seed=trial) + 0.5 * rng.standard_normal(param_count(cfgA))
        x = rng.uniform(-np.pi, np.pi, size=cfgA.n)
        pa, pb = prepare(cfgA, p, x), prepare(cfgB, p, x)
        # pre-coupling substates differ (up to a global phase even)
        ovl = abs(np.vdot(pa.psiA_pre, pb.psiA_pre))
        assert ovl < 1 - 1e-3, ovl
        assert np.max(np.abs(full_features(pa, obs) - full_features(pb, obs))) > 1e-3
    # the B block really applies CNOTs: with zero angles on |+0> it must produce a Bell pair
    psi = qsim.apply_1q(qsim.zero_state(2), qsim.H, 0, 2)
    out = local_var_layer(psi, np.zeros(4), 2, 1, "B")
    assert np.allclose(np.abs(out) ** 2, [0.5, 0, 0, 0.5])
    # ... whereas the A block (CZ) leaves |+0> a product state
    outA = local_var_layer(psi, np.zeros(4), 2, 1, "A")
    assert np.allclose(np.abs(outA) ** 2, [0.5, 0, 0.5, 0])


def test_unknown_ansatz_rejected():
    cfg = QNNConfig(ansatz="Z")
    try:
        prepare(cfg, init_params(cfg), np.zeros(cfg.n))
    except ValueError:
        return
    raise AssertionError("unknown ansatz must raise ValueError")


if __name__ == "__main__":
    test_ansatz_A_bit_identical_to_pre_change_reference()
    test_ansatz_B_param_layout_matches_A()
    test_ansatz_B_exact_reconstruction_equals_uncut()
    test_ansatz_B_differs_from_A()
    test_unknown_ansatz_rejected()
    print("ansatz-B tests passed: A bit-identical to reference; B reconstruction exact (<1e-10); B != A.")
